<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Url;
use Drupal\moderation_notes\ModerationNoteInterface;

/**
 * Implements hook_entity_view_alter().
 */
function moderation_notes_entity_view_alter(&$build, EntityInterface $entity, \Drupal\Core\Entity\Display\EntityViewDisplayInterface $display) {
  if (!_moderation_notes_access($entity)) {
    return;
  }

  // Load notes for this entity.
  $ids = \Drupal::entityQuery('moderation_note')
    ->condition('entity_type', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->condition('entity_langcode', $entity->language()->getId())
    ->condition('entity_view_mode_id', $display->getOriginalMode())
    ->notExists('parent')
    ->execute();

  /** @var \Drupal\moderation_notes\ModerationNoteInterface[] $notes */
  $notes = \Drupal::entityTypeManager()->getStorage('moderation_note')->loadMultiple($ids);
  foreach ($notes as $note) {
    $setting = [
      'field_id' => _moderation_notes_generate_field_id($note),
      'id' => $note->id(),
      'quote' => $note->getQuote(),
      'quote_offset' => $note->getQuoteOffset(),
    ];
    $build['#attached']['drupalSettings']['moderation_notes'][$note->id()] = $setting;
  }
}

/**
 * Implements hook_entity_delete().
 */
function moderation_notes_entity_delete(EntityInterface $entity) {
  // Load and delete all associated notes for this entity.
  $ids = \Drupal::entityQuery('moderation_note')
    ->condition('entity_type', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->execute();
  $notes = \Drupal::entityTypeManager()->getStorage('moderation_note')->loadMultiple($ids);
  \Drupal::entityTypeManager()->getStorage('moderation_note')->delete($notes);
}

/**
 * Implements hook_menu_local_tasks_alter().
 */
function moderation_notes_menu_local_tasks_alter(&$data, $route_name) {
  // If this is an admin route, return early.
  // @todo Why doesn't Outside In behave nicely with Seven?
  if (\Drupal::service('router.admin_context')->isAdminRoute()) {
    return;
  }

  // Get the current Entity.
  // @todo Support other entities. What's the generic way of doing this?
  /** @var \Drupal\Core\Entity\ContentEntityInterface $entity */
  if (!$entity = \Drupal::routeMatch()->getParameter('node')) {
    return;
  }

  // Check to see if there are associated notes for this Entity.
  $count = \Drupal::entityQuery('moderation_note')
    ->condition('entity_type', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->notExists('parent')
    ->count()
    ->execute();

  if ($count) {
    $params = [
      'entity_type' => $entity->getEntityTypeId(),
      'entity' => $entity->id(),
    ];
    $data['tabs'][0]['moderation_notes.list'] = [
      '#theme' => 'menu_local_task',
      '#link' => [
        'title' => t('View Notes'),
        'url' => Url::fromRoute('moderation_notes.list', $params),
        'localized_options' => [
          'attributes' => [
            'class' => ['use-ajax'],
            'data-dialog-type' => 'dialog',
            'data-dialog-renderer' => 'offcanvas',
          ],
        ],
      ],
      '#attached' => ['library' => ['moderation_notes/main'],
      ],
    ];
  }

}

/**
 * Implements hook_moderation_sidebar_alter().
 */
function moderation_notes_moderation_sidebar_alter(array &$build, EntityInterface $entity) {
  // Check to see if there are associated notes for this Entity.
  $count = \Drupal::entityQuery('moderation_note')
    ->condition('entity_type', $entity->getEntityTypeId())
    ->condition('entity_id', $entity->id())
    ->notExists('parent')
    ->count()
    ->execute();

  if ($count) {
    $params = [
      'entity_type' => $entity->getEntityTypeId(),
      'entity' => $entity->id(),
    ];
    $build['moderation_notes'] = [
      '#type' => 'link',
      '#url' => Url::fromRoute('moderation_notes.list', $params),
      '#title' => t('View Notes'),
      '#attributes' => [
        'class' => [
          'use-ajax',
          'moderation-sidebar-link',
          'button'
        ],
        'data-dialog-type' => 'dialog',
        'data-dialog-renderer' => 'offcanvas',
      ],
    ];
  }
}

/**
 * Implements hook_preprocess_HOOK() for field templates.
 */
function moderation_notes_preprocess_field(&$variables) {
  $variables['#cache']['contexts'][] = 'user.permissions';

  $element = $variables['element'];
  /** @var $entity \Drupal\Core\Entity\EntityInterface */
  $entity = $element['#object'];
  /** @var \Drupal\Core\Field\FieldItemList $field_list */
  $field_list = $element['#items'];
  $field_definition = $field_list->getFieldDefinition();

  // Check access for moderation notes.
  if (!_moderation_notes_access($entity)) {
    return;
  }

  // Check the field type - we only support text fields at this time.
  $supported_types = ['string', 'text', 'text_long', 'text_with_summary'];
  if (!in_array($field_definition->getType(), $supported_types, TRUE)) {
    return;
  }

  $definition = $entity->getFieldDefinition($element['#field_name']);
  if (!$definition->isComputed()) {
    $variables['#attached']['library'][] = 'moderation_notes/main';
    $variables['attributes']['data-moderation-notes-field-id'] = $entity->getEntityTypeId() . '/' . $entity->id() . '/' . $element['#field_name'] . '/' . $element['#language'] . '/' . $element['#view_mode'];
  }
}

/**
 * Access callback to determine if an Entity can be annotated.
 *
 * @param \Drupal\Core\Entity\EntityInterface $entity
 *   The Entity to check.
 *
 * @return bool
 *   TRUE if the current user can access the Entity, FALSE otherwise.
 */
function _moderation_notes_access(EntityInterface $entity) {
  /** @var \Drupal\content_moderation\ModerationInformation $moderation_information */
  $moderation_information = \Drupal::service('content_moderation.moderation_information');

  // Check if this is the latest moderated revision and if the user has access.
  // @todo When Quick Edit is rendering an entity after an edit, the revision
  // ID is null. Investigate and/or file a core issue.
  return \Drupal::currentUser()->hasPermission('access moderation notes')
  && $moderation_information->isModeratedEntity($entity)
  && ($entity->getRevisionId() === null || $moderation_information->isLatestRevision($entity))
  && !$entity->isNew();
}

/**
 * Implements hook_theme().
 */
function moderation_notes_theme() {
  return [
    'moderation_note' => [
      'render element' => 'elements',
    ],
    'moderation_note__preview' => [
      'base hook' => 'moderation_note',
    ],
  ];
}

/**
 * Implements hook_theme_suggestions_HOOK().
 */
function moderation_notes_theme_suggestions_moderation_note(array $variables) {
  return [
    'moderation_note__' . $variables['elements']['#view_mode'],
  ];
}

/**
 * Prepares variables for moderation_note templates.
 *
 * Default template: moderation-note.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An array of elements to display in view mode.
 */
function template_preprocess_moderation_note(&$variables) {
  $variables['moderation_note'] = $variables['elements']['#moderation_note'];
  /** @var \Drupal\moderation_notes\ModerationNoteInterface $note */
  $note = $variables['moderation_note'];
  $variables['text'] = $note->getText();
  $variables['quote'] = $note->getQuote();
  $variables['created'] = $note->getCreatedTime();
  $variables['created_pretty'] = _moderation_notes_pretty_time($note->getCreatedTime());
  $variables['updated'] = $note->getChangedTime();
  $variables['updated_pretty'] = _moderation_notes_pretty_time($note->getChangedTime());
  $owner = $note->getOwner();
  $variables['author_name'] = $owner->getDisplayName();
  $variables['author_link'] = $owner->toLink()->toRenderable();
  $variables['author_username'] = $owner->label();
  $variables['author_picture'] = user_view($owner, 'compact');
  $variables['parent'] = $note->getParent();
  $variables['moderated_entity_link'] = $note->getModeratedEntity()->toLink();

  // Attributes.
  $variables['attributes']['class'][] = 'moderation-note';
  $variables['attributes']['data-moderation-note-id'] = $note->id();
  if ($note->getParent()) {
    $variables['attributes']['class'][] = 'moderation-note-reply';
  }

  $params = ['moderation_note' => $note->id()];

  // We show note actions inline with the note, if the user has access.
  if ($note->access('update')) {
    $url = Url::fromRoute('moderation_notes.edit', $params);
    $variables['edit_button'] = [
      '#type' => 'link',
      '#title' => t('Edit'),
      '#url' => $url,
      '#attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'dialog',
        'data-dialog-renderer' => 'offcanvas',
      ],
    ];
  }

  if ($note->access('delete')) {
    $url = Url::fromRoute('moderation_notes.delete', $params);
    $variables['delete_button'] = [
      '#type' => 'link',
      '#title' => t('Delete'),
      '#url' => $url,
      '#attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'dialog',
        'data-dialog-renderer' => 'offcanvas',
      ],
    ];
  }

  // We don't support view modes, but if a note is rendered with "preview" we
  // add a button to view the "full" note (the note with replies).
  if ($note->access('view')) {
    $url = Url::fromRoute('moderation_notes.view', $params);
    $url->setOption('query', ['from-preview' => '1']);
    $variables['view_button'] = [
      '#type' => 'link',
      '#title' => t('View Full Note'),
      '#url' => $url,
      '#attributes' => [
        'class' => ['use-ajax'],
        'data-dialog-type' => 'dialog',
        'data-dialog-renderer' => 'offcanvas',
      ],
    ];
  }
}

/**
 * Displays a timestamp in a human-readable fashion.
 *
 * @param int $time
 *   A timestamp.
 *
 * @return \Drupal\Core\StringTranslation\TranslatableMarkup
 *   Markup representing a formatted time.
 */
function _moderation_notes_pretty_time($time) {
  $time = (int) $time;
  $too_old = strtotime('-1 month');
  // Show formatted time differences for edits younger than a month.
  if ($time > $too_old) {
    $diff = \Drupal::service('date.formatter')->formatTimeDiffSince($time, ['granularity' => 1]);
    $time_pretty = t('@diff ago', ['@diff' => $diff]);
  }
  else {
    $date = date('m/d/Y - h:i A', $time);
    $time_pretty = t('on @date', ['@date' => $date]);
  }
  return $time_pretty;
}

/**
 * Generates a field ID for a given note.
 *
 * @param \Drupal\moderation_notes\ModerationNoteInterface $note
 *   The note to generate the field ID from.
 *
 * @return string
 *   A string representing a note's field ID.
 */
function _moderation_notes_generate_field_id(ModerationNoteInterface $note) {
  return $note->getModeratedEntityTypeId() . '/' . $note->getModeratedEntityId() . '/' . $note->getEntityFieldName() . '/' . $note->getEntityLanguage() . '/' . $note->getEntityViewModeId();
}
